// <auto-generated />
namespace EasyDOC.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MasterProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MasterProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201407311750256_MasterProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
