// <auto-generated />
namespace EasyDOC.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TaskLinkFixDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskLinkFixDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201404031233314_TaskLinkFixDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
