// <auto-generated />
namespace EasyDOC.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class OverwritableFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverwritableFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201403140959363_OverwritableFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
